### ISSUE TITLE
Feature Request: Support for routing/addressable navigation

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-sdk#137]
Are there any plans for adding support to allow for resolving routes & navigating to things within mobile via direct url? For example, allowing a url such as https://demo.crmcloud.infor.com/slxmobile/#_account_detail;AGHEA0002669 to navigate to the account_detail view and display the record for the ID?

**Comment by jbest84** [comment]
We have a next-gen branch where we are adding a proper router. If you are using an older release and want to generate links to mobile, you can use the redirectTo system have have built in:

https://your-mobilesite.test/#_/redirectTo/account_detail;AGHEA0002669

    #_/redirectTo/<view ID>;<Entity Id>

**Comment by RyanFarley** [comment]
That is great news. Also, thanks for the tip about the redirectTo
