### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-sdk#138]
When I do an npm install I get ENOTFOUND errors on npm.infor.com (which doesn't seem to be a publicly accessible address). I get the same on argos-saleslogix as well.

Attaching npm log - [npm-debug.log.txt](https://github.com/Saleslogix/argos-sdk/files/1257602/npm-debug.log.txt)

**Comment by jbest84** [comment]
Yeah - This is expected on the develop branch right now. We are in talks with legal internally to get a license setup for Soho. Once this is done, we hope to copy it into the libraries folder. If we don't get permission in time for the 4.0 release, you can copy Soho from the bundle.

**Comment by RyanFarley** [comment]
I figured that was the case. I saw the wiki post about 4.0 changes, so I pulled develop to test some things. I figured by the time of the actual release they'll be added as file libraries. I'll close this for now and be patient for the 4.0 release 👍

**Comment by jbest84** [comment]
@RyanFarley - We have worked out a few issues with legal now. The SOHO UI component runtime will be linked to from an official Infor CDN, we will no longer provide them in the bundle or a private NPM repository. A license file for the SOHO runtime is now in the project root. Lastly, argos-sdk and argos-saleslogix have gone back to the Apache2 license. They were a more strict Swiftpage license for a while.

The changes are live on the develop branch. Just note that QA has not validated the CDN usage yet.

**Comment by RyanFarley** [comment]
Thanks for letting me know @jbest84 I will take a look!

**Comment by RyanFarley** [comment]
@jbest84 Just wanted to let you know that all worked great with the dependencies. BTW, love the new UI, this is awesome. IMO it's time to drop the full web client and go all mobile 💥 😄

**Comment by jbest84** [comment]
Thank you for the feedback. I passed it along to the team.
