### ISSUE TITLE
Problems with customizations

### ISSUE THREAD

**Issue by Iveth** [Saleslogix/argos-sdk#139]
Good afternoon, I installed the last version of SDK in my Infor Version Mobile, but I have problems, when I try to put my customization, the folder argos-sample doesn't work in this version, Could you help me, please, I need to that my customization work in this version.

Regards.

**Comment by jbest84** [comment]
Ensure you switch to the 3.6.x branch once you clone. The latest develop branch is for an upcoming 4.0 release.

`git checkout -b 3.6.x origin/3.6.x`
