### ISSUE TITLE
Request: Keep SData version separate from Mongoose API version

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-sdk#140]
Just wanted to get this request out there early. When you start looking at porting things like argos.Store.SData from SData to the Mongoose API (good luck 😁), please do retain the SData version as well. Ideally, there would be a config option or something that routes to the appropriate store type or something, but at minimum a separate branch for one of the versions or something. 

Since it's been said that current CRM will be supported for at least 4 years, it's crucial we retain an SData version of mobile during that time as well. I am sure that you're already planning on all this, but still I wanted to make sure this was put there early before work was started just to be sure.

Thanks,
Ryan

**Comment by jbest84** [comment]
I have not yet heard any plans to port argos to Mongoose. We should be shipping 4.0 for SData later this year. The Hook and Loop team is working on the IOS version of mobile for Mongoose, and the CRM mobile devs are working on the Android version, along with a new API that will have adapters to SData/Mongoose. The goal here is to support the new native apps on both API's.

I believe the Mongoose framework is responsive down to mobile, so I am guessing it can handle the mobile web scenario. If we do end up porting argos to Mongoose, we will certainly use a new dojo store and not trample on the SData version. We already use generic memory stores for certain views.

**Comment by RyanFarley** [comment]
I guess we'll have to see how it all plays out. At the boot camp in ATL there were several times that it was mentioned that they will not be using the mongoose mobile device views - current Mongoose itself isn't responsive, but you can create a layout of a form for a specific device type, such as for mobile or tablets, however, they mentioned their current plans were not to use that and instead stick with the current mobile client (in addition to the native app from hook & loop)

There's a lot of issues with the mongoose REST API that will not do well with the argos client, such as not being able to request or update a data hierarchy (you'd have to send a separate request for each related entity, such as account, addresses, phones, etc etc, rather than get/post it all in one request and also the inability to invoke service operations / execute entity methods. 

Anyway, since it was mentioned (by several different Infor people) that the argos client would continue to be used in the mongoose CRM scenario, I just wanted to make sure we didn't lose the SData version in the process. 

Thanks Jason. Looking forward to v4 getting released (I would have much rather seen it evolve to replace the full CRM web client instead of mongoose).
