### ISSUE TITLE
Attachment Uploading

### ISSUE THREAD

**Issue by Veodin** [Saleslogix/argos-sdk#158]
When attempting to upload attachments using iOS 13 users are no longer prompted to choose between the photo library, taking a photo, or launching the file browser. You are instead directed immediately to the iOS file browser and no files are selectable (all files are greyed out). 

This issues is caused by the following line of code in FileSelect.js
`<input type="file" data-dojo-attach-point="btnFileSelect" name="file-input" size="71" accept="*/*"/>`

Removing the 'accept 'attribute appears to restore the original functionality.

**Comment by jbest84** [comment]
Thanks for the report. It looks like this might be a Safari bug in the latest IOS. Seeing other reports on this:

- https://github.com/lionheart/openradar-mirror/issues/19227
- https://stackoverflow.com/questions/58302568/attribute-accept-doesnt-work-properly-on-ios-13-and-higher-input-type-file

In our case, we don't restrict the file type anyways. I will look into just removing the accept attribute as you suggest.

**Comment by jbest84** [comment]
https://github.com/Saleslogix/argos-sdk/commit/2b50db5edc602b7a343db6412b1cc19ac1145506
