### ISSUE TITLE
23 - DateTimeSection.js - If next week is next month - not showing as next week

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-sdk#16]
Subject says it..
EX: Friday is "next month" - Aug - and there's activities scheduled for Monday (Aug 5th) - they show up as next month but should show up as next week.

**Comment by rjledger** [comment]
Update - noticed the following - Line 130:
      if (valueWeek = this.currentWeek + 1) {
                            key = "NextWeek";
                        } else {

should be :
 if (valueWeek == this.currentWeek + 1) {
                            key = "NextWeek";
                        } else {

**Comment by jbest84** [comment]
@rjledger Thanks for the heads up. I will add this note to our internal defect on it.

**Comment by rjledger** [comment]
You are welcome.
