### ISSUE TITLE
Sandboxed frame on argos.Views.Link needs allow-popups for embedded Google maps to work

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-sdk#167]
Currently, when you click on an address and it opens the google maps link in argos.Views.Link to display the embedded map, you cannot click the "View Larger Map" and "Directions" link in the embedded map due to the sandboxed frame not having proper permissions set.

To fix, add "allow-popups allow-popups-to-escape-sandbox" to sandboxed frame

Thanks,
Ryan

**Comment by jbest84** [comment]
Thank you for the feedback Ryan. I will get this filed with our internal JIRA so it can go out with the next release.

**Comment by jbest84** [comment]
INFORCRM-24295
