### ISSUE TITLE
Issue with search bar on Android devices in mobile 4.2.0

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-sdk#198]
I have a client with many Android users and many of them experience the same issue with the search field on all list pages They click the search icon and it expands the search box, but then it's like it loses focus and collapses, then gets focus and expands, then loses focus and collapses, etc. This continues forever until they click somewhere else. So basically, they can't search because if they click into the search field it expands/collapses/expands/collapses etc.

Have you see this happen? The admin of this system who reported this uses an Android Galaxy S20 FE, but she has tried 3 other Android devices and they all have this same issue. I can't reproduce on iPhone or on the Android emulators I've tried, but have witnessed it happening via zoom calls with this person.

This is a weird one, I don't even know where to start with fixing this, maybe making the search box static at the top and not expand/collapse?

Is this something you've heard of or seen?

**Comment by jbest84** [comment]
Yeah, this is a known issue. I fixed it on the develop branch (which will eventually become 4.3):

https://github.com/Saleslogix/argos-sdk/commit/e935639567331315e03dabcc9d8c30b365b761fe

If you don't want to bundle it yourself, support should have a UTT for it:

INFORCRM-25083 on Mobile 4.1 or 4.2

**Comment by RyanFarley** [comment]
Awesome, huge thanks.
