### ISSUE TITLE
Update to latest dojo releases?

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-sdk#2]
are there plans to update to the latest dojo - vers 1.9 ?

**Comment by jbest84** [comment]
Not for any of the 2.x releases. We are sticking with 1.7 to match the web client.

**Comment by rjledger** [comment]
Should I expect any issues if I drop the 1.9 in my system?

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
Was there something specific in 1.9 that you wanted to have?

**Comment by jbest84** [comment]
@rjledger We have re-considered and will upgrade dojo to 1.9 in the next release (2.3).

**Comment by rjledger** [comment]
@jbest84 - Sounds great!

**Comment by rjledger** [comment]
I see the latest dojo (1.9x) is in the 2.3 code
