### ISSUE TITLE
Not enough years displayed in date picker

### ISSUE THREAD

**Issue by damonfutter** [Saleslogix/argos-sdk#51]
In the date picker, there are no 'past' years in the drop-down for the year.
![datepicker](https://f.cloud.github.com/assets/1250921/1715954/35169424-61ba-11e3-8bec-426aa8766cd1.png)

This makes it difficult to choose dates for years in the past.

If the comments on lines 220-221 of "src/Calendar.js" are accurate, it should be displaying 10 years into the past and 10 years into the future(e.g. 2003 -> 2023).  In that case, it looks as if there is an incorrectly placed bracket on line 220.

```
(this.year < today.year()) - 10 ? this.year : today.year() - 10,
```

should be

```
(this.year < today.year() - 10) ? this.year : today.year() - 10,
```

**Comment by jbest84** [comment]
@damonfutter Thank you for the report and finding the fix. I will push the commit asap.
